/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2019-02-11 02:03:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../home/top.jsp", out, false);
      out.write("\n");
      out.write("<link rel=\"stylesheet\" \n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${css}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/employee/register.css\" />\n");
      out.write("<div class=\"grid-item\" id=\"side_menu\">\n");
      out.write(" \t<h1><font style=\"font-size: 30px\">회원 등록</font></h1>\n");
      out.write("</div>\n");
      out.write(" <div>\n");
      out.write(" <form id=\"signup_form\">\n");
      out.write("  <h1>회원정보</h1>\n");
      out.write("  \n");
      out.write("   \t<div class=\"input-group input-group-lg\">\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">ID</span>\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" placeholder=\"ID\" aria-describedby=\"sizing-addon1\" \n");
      out.write("  \t\t\t\tname=\"customId\" id=\"customId\"/>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"input-group input-group-lg\">\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">이름</span>\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" placeholder=\"Username\" aria-describedby=\"sizing-addon1\" \n");
      out.write("  \t\t\t\tname=\"cname\" id=\"cname\"/>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"input-group input-group-lg\">\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">비밀번호</span>\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" placeholder=\"Password\" aria-describedby=\"sizing-addon1\" \n");
      out.write("  \t\t\t\tname=\"cpassword\" id=\"cpassword\"/>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"input-group input-group-lg\">\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">주민번호</span>\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" placeholder=\"SSN\" aria-describedby=\"sizing-addon1\" \n");
      out.write("  \t\t\t\tname=\"ssn\" id=\"ssn\"/>\n");
      out.write("\t</div>\n");
      out.write("\t\t<div class=\"input-group input-group-lg\">\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">전화번호</span>\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" placeholder=\"phone\" aria-describedby=\"sizing-addon1\" \n");
      out.write("  \t\t\t\tname=\"phone\" id=\"phone\"/>\n");
      out.write("\t</div>\n");
      out.write("\t\t<div class=\"input-group input-group-lg\">\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">사진</span>\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" placeholder=\"photo\" aria-describedby=\"sizing-addon1\" \n");
      out.write("  \t\t\t\tname=\"photo\" id=\"photo\"/>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"input-group input-group-lg\">\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">지번주소</span>\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" placeholder=\"city\" aria-describedby=\"sizing-addon1\" \n");
      out.write("  \t\t\t\tname=\"city\" id=\"city\"/>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"input-group input-group-lg\">\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">상세주소</span>\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" placeholder=\"Address\" aria-describedby=\"sizing-addon1\" \n");
      out.write("  \t\t\t\tname=\"addr\" id=\"addr\"/>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"input-group input-group-lg\">\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">우편번호</span>\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" placeholder=\"pcode\" aria-describedby=\"sizing-addon1\" \n");
      out.write("  \t\t\t\tname=\"pcode\" id=\"pcode\"/>\n");
      out.write("\t</div>\n");
      out.write("  <div class=\"row\">\n");
      out.write("  <div class=\"col-lg-6\">\n");
      out.write("    <div class=\"input-group\">\n");
      out.write("      <span class=\"input-group-btn\">\n");
      out.write("        <button class=\"btn btn-default\" type=\"submit\" id=\"confirm_btn\">등록</button>\n");
      out.write("      </span>\n");
      out.write("          <span class=\"input-group-btn\">\n");
      out.write("        <button class=\"btn btn-default\" type=\"reset\" id=\"cancel_btn\">취소</button>\n");
      out.write("      </span>\n");
      out.write("    </div>\n");
      out.write("   </div>\n");
      out.write("</div>\n");
      out.write("\t<input type=\"hidden\" name=\"cmd\" value=\"signup\" />\n");
      out.write("\t<input type=\"hidden\" name=\"page\" value=\"signin\" />\n");
      out.write("</form>\n");
      out.write("</div>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../home/bottom.jsp", out, false);
      out.write("\n");
      out.write("    <script>\n");
      out.write(" \t\t $('#confirm_btn').click(function(){\n");
      out.write(" \t\t\tvar customId = $('#customId').val();\n");
      out.write(" \t\t\tvar cname = $('#cname').val();\n");
      out.write(" \t\t\tvar cpassword = $('#cpassword').val();\n");
      out.write(" \t\t\tvar ssn = $('#ssn').val();\n");
      out.write(" \t\t\tvar phone = $('#phone').val();\n");
      out.write(" \t\t\tvar photo = $('#photo').val();\n");
      out.write("\t  \t\tvar city = $('#city').val();\n");
      out.write("\t  \t\tvar addr = $('#addr').val();\n");
      out.write("\t  \t\tvar pcode = $('#pcode').val();\n");
      out.write("\t  \t\t\n");
      out.write("\t  \t\t$('#signup_form').attr('action','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer.do').submit;\n");
      out.write(" \t\t\n");
      out.write("\t\t});\n");
      out.write("\t  \t\t\n");
      out.write("// \t  \t\tif(empno === ''||ename === ''||\n");
      out.write("//\t  \t\t\t\temag === ''||ebd === ''){\n");
      out.write("//\t  \t\t\talert('필수 입력값이 없습니다.');\t\n");
      out.write("//\t  \t\t} else  {\n");
      out.write("//\t  \t\t\talert('else 로 넘어왔다~.');\n");
      out.write("//\t  \t\t\t$('#register_form').attr('action','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/employee.do').submit;\n");
      out.write("//\t  \t\t}\n");
      out.write("// \t\t\t});\n");
      out.write("\n");
      out.write("//  \t\t$('#cancel_btn').click(function(){\n");
      out.write("//  \t\t\talert('취소버튼 클릭'); \n");
      out.write(" // \t\t\t});   */\n");
      out.write("  </script>\n");
      out.write("\n");
      out.write("\n");
      out.write(" <!-- employeeID, manager,name, birthDate, photo, notes-->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
