/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2019-02-21 11:50:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class pro_005fupload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/hanbit/workspace/jee-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/BitTrader/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1548376978453L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../home/top.jsp", out, false);
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" \r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${css}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/list.css\" />\r\n");
      out.write("<div class=\"grid-item\" id=\"navi_bar\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../home/post-navi-bar.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"grid-item\" id=\"side_menu\">\r\n");
      out.write(" \t<h1><font style=\"font-size: 30px\">상품 등록</font></h1>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-xs-6\">\r\n");
      out.write("<div class=\"grid-item\" id=\"content\">\r\n");
      out.write(" \t<div class=\"grid-item\" id=\"content\">\r\n");
      out.write(" \t<h1>상품 정보</h1>\r\n");
      out.write("  \t\t<form id=\"form\"  >\r\n");
      out.write("\t  \t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${image.imgName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('.');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${image.imgExtention}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"height: 380px; width: 450px;\"/>\r\n");
      out.write("\t  \t\t<input type=\"file\" name=\"file_upload\" />\r\n");
      out.write("\t  \t\t<input type=\"submit\" id=\"file_upload_btn\" />\r\n");
      out.write("\t  \t\t<input type=\"hidden\" name=\"cmd\" value=\"pro_file_upload\"/>\r\n");
      out.write("\t  \t\t<input type=\"hidden\" name=\"page\" value=\"detail\"/>\r\n");
      out.write("\t  \t</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-xs-6\">\r\n");
      out.write("  \t<div class=\"grid-item\" id=\"content\">\r\n");
      out.write(" <div>\r\n");
      out.write(" <form id=\"pro_upload_form\">\r\n");
      out.write("  <h1>상품 정보</h1>\r\n");
      out.write("  \r\n");
      out.write("   \t<div class=\"input-group input-group-lg\">\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t<!--  -->\r\n");
      out.write(" <!-- \t\t<div class=\"dropdown\">\r\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">ProductID\r\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" aria-label=\"...\" id=\"product_id\"></input></span>\r\n");
      out.write("    <button class=\"btn btn-default dropdown-toggle\" id=\"mystatus\" value=\"title\" type=\"button\" data-toggle=\"dropdown\" aria-expanded=\"true\">\r\n");
      out.write("    ProductID\r\n");
      out.write("    <span class=\"caret\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <ul id=\"mytype\" class=\"dropdown-menu\" role=\"menu\" aria-labelledby=\"searchType\">\r\n");
      out.write("        <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\" value=\"1000\">삼성</a></li>\r\n");
      out.write("        <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\" value=\"1001\">애플</a></li>\r\n");
      out.write("        <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\" value=\"1002\">LG</a></li>\r\n");
      out.write("        <li class=\"divider\"></li>\r\n");
      out.write("        <li><a href=\"#\">개인 판매자</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div> -->\r\n");
      out.write(" \t\t<!--  -->\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t  <div class=\"col-lg-6\">\r\n");
      out.write("    <div class=\"input-group\">\r\n");
      out.write("    \t <span class=\"input-group-addon\" id=\"sizing-addon1\">ProductID</span>\r\n");
      out.write("    \t  <input type=\"text\" class=\"form-control\" aria-label=\"...\" id=\"product_id\" value=\"\">\r\n");
      out.write("      <div class=\"input-group-btn\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\">ID List <span class=\"caret\"></span></button>\r\n");
      out.write("        <ul class=\"dropdown-menu dropdown-menu-right\" role=\"menu\" id=\"select_pro_id\">\r\n");
      out.write("          <li id=\"pro_id_1\"><div class=\"grid-item\" value=\"1000\">삼성</div></li>\r\n");
      out.write("          <li><div class=\"grid-item\" value=\"1001\">애플</div></li>\r\n");
      out.write("          <li><div class=\"grid-item\" value=\"1002\">LG</div></li>\r\n");
      out.write("          <li><div class=\"grid-item\" value=\"1003\">화웨이</div></li>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div><!-- /btn-group -->\r\n");
      out.write("    </div><!-- /input-group -->\r\n");
      out.write("  </div>\r\n");
      out.write(" \t\t <!-- <input type=\"text\" class=\"form-control\" placeholder=\"ID\" aria-describedby=\"sizing-addon1\" \r\n");
      out.write("  \t\t\t\tname=\"customId\" id=\"customId\"/> -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"input-group input-group-lg\">\r\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">이름</span>\r\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" placeholder=\"Username\" aria-describedby=\"sizing-addon1\" \r\n");
      out.write("  \t\t\t\tname=\"cname\" id=\"cname\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"input-group input-group-lg\">\r\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">비밀번호</span>\r\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" placeholder=\"Password\" aria-describedby=\"sizing-addon1\" \r\n");
      out.write("  \t\t\t\tname=\"cpassword\" id=\"cpassword\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"input-group input-group-lg\">\r\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">주민번호</span>\r\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" placeholder=\"SSN\" aria-describedby=\"sizing-addon1\" \r\n");
      out.write("  \t\t\t\tname=\"ssn\" id=\"ssn\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div class=\"input-group input-group-lg\">\r\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">전화번호</span>\r\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" placeholder=\"phone\" aria-describedby=\"sizing-addon1\" \r\n");
      out.write("  \t\t\t\tname=\"phone\" id=\"phone\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div class=\"input-group input-group-lg\">\r\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">사진</span>\r\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" placeholder=\"photo\" aria-describedby=\"sizing-addon1\" \r\n");
      out.write("  \t\t\t\tname=\"photo\" id=\"photo\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"input-group input-group-lg\">\r\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">지번주소</span>\r\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" placeholder=\"city\" aria-describedby=\"sizing-addon1\" \r\n");
      out.write("  \t\t\t\tname=\"city\" id=\"city\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"input-group input-group-lg\">\r\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">상세주소</span>\r\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" placeholder=\"Address\" aria-describedby=\"sizing-addon1\" \r\n");
      out.write("  \t\t\t\tname=\"addr\" id=\"addr\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"input-group input-group-lg\">\r\n");
      out.write(" \t\t <span class=\"input-group-addon\" id=\"sizing-addon1\">우편번호</span>\r\n");
      out.write(" \t\t <input type=\"text\" class=\"form-control\" placeholder=\"pcode\" aria-describedby=\"sizing-addon1\" \r\n");
      out.write("  \t\t\t\tname=\"pcode\" id=\"pcode\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("  <div class=\"col-lg-6\">\r\n");
      out.write("    <div class=\"input-group\">\r\n");
      out.write("      <span class=\"input-group-btn\">\r\n");
      out.write("        <button class=\"btn btn-default\" type=\"submit\" id=\"confirm_btn\">등록</button>\r\n");
      out.write("      </span>\r\n");
      out.write("          <span class=\"input-group-btn\">\r\n");
      out.write("        <button class=\"btn btn-default\" type=\"reset\" id=\"cancel_btn\">취소</button>\r\n");
      out.write("      </span>\r\n");
      out.write("    </div>\r\n");
      out.write("   </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("\t<input type=\"hidden\" name=\"cmd\" value=\"signup\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"page\" value=\"signin\" />\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write(" </div>\r\n");
      out.write("</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../home/bottom.jsp", out, false);
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write(" \t\t $('#confirm_btn').click(function(){\r\n");
      out.write(" \t\t\tvar customId = $('#customId').val();\r\n");
      out.write(" \t\t\tvar cname = $('#cname').val();\r\n");
      out.write(" \t\t\tvar cpassword = $('#cpassword').val();\r\n");
      out.write(" \t\t\tvar ssn = $('#ssn').val();\r\n");
      out.write(" \t\t\tvar phone = $('#phone').val();\r\n");
      out.write(" \t\t\tvar photo = $('#photo').val();\r\n");
      out.write("\t  \t\tvar city = $('#city').val();\r\n");
      out.write("\t  \t\tvar addr = $('#addr').val();\r\n");
      out.write("\t  \t\tvar pcode = $('#pcode').val();\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\t  \t\t$('#signup_form').attr('action','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer.do').submit;\r\n");
      out.write(" \t\t});\r\n");
      out.write(" \t\t \r\n");
      out.write(" \t\t \r\n");
      out.write("\t  \t$('#pro_id_1').attr('style','cursor:pointer').on('click', function() {\r\n");
      out.write("\t  \t\t   // 버튼에 선택된 항목 텍스트 넣기 \r\n");
      out.write("\t  \t\t    $('#product_id').text($(this).text());\r\n");
      out.write("\t  \t\t  alert($(this).attr('value'));\r\n");
      out.write("\t\t});\r\n");
      out.write("\t  \t\r\n");
      out.write("\t  \t/*  */\r\n");
      out.write("\t  \t\r\n");
      out.write("\t  \t$('#mytype li > a').on('click', function() {\r\n");
      out.write("    // 버튼에 선택된 항목 텍스트 넣기 \r\n");
      out.write("   \t\t\t $('#select_pro_id').text($(this).text());\r\n");
      out.write("        \r\n");
      out.write("    // 선택된 항목 값(value) 얻기\r\n");
      out.write("   \t\t \talert($(this).attr('value'));\r\n");
      out.write("    \t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- employeeID, manager,name, birthDate, photo, notes-->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
